version: '3'
services:
  my-app:
    image: 459488287898.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0.1
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 127.0.0.1:8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: always
volumes:
  mongo-data:
    driver: local

