apiVersion: apps/v1
kind: Deployment # what I want to create
metadata:
  name: nginx-deployment # name of the deployment
  labels:
    app: nginx
spec: # specification for deployment
  replicas: 2 # how many replicas of the pod
  selector:
    matchLabels:
      app: nginx
  template: # blueprint for the pods
    metadata:
      labels:
        app: nginx
    spec: # specification for pods
      containers:
        - name: nginx # we want one container
          image: nginx:1.16-alpine
          ports:
            - containerPort: 8080 # bind that on port 80
